### ISSUE TITLE
Fix YT Links

### ISSUE THREAD

**Issue by dag7dev** [An-dz/VSDGenerator#2]
Today I discovered this ext: thanks for this, it is really nice!

However there is a thing that it is really annoying: when dealing with youtube links, 90% of the time the addon fails to fetch the image, so it will add a blank thumbnail.

I suggest to implement: "in case URL I am dealing with, is made with this structure "*.youtube.com/watch?v=*", then download and set the thumbnail from "http://img.youtube.com/vi/[video-id]/maxresdefault.jpg"

**Comment by dag7dev** [comment]
Example links to be clearer: https://www.youtube.com/watch?v=QqTpnRHklpA and https://www.youtube.com/watch?v=W6qriAJy7fs
Addon doesn't fetch 90% of time (it works with no problem for this: https://www.youtube.com/watch?v=XFUHGT3qWAw)

**Comment by An-dz** [comment]
I've made a complete rewrite of the code, I'm still testing locally but will release once I feel confident it works, I'll test YouTube probably in the weekend and if it goes well I'll release v2.

**Comment by dag7dev** [comment]
Glad to hear some news!
Cant wait to try it out!

**Comment by An-dz** [comment]
Version 2.0 has been [released](https://github.com/An-dz/VSDGenerator/releases/tag/v2.0) and my tests have not failed for any of the provided links.
